# Generated by Django 2.1.4 on 2018-12-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudex', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crudex',
            new_name='Product',
        ),
    ]
